name: Scrape Jobs
env:
  SLACKURL: ${{ secrets.SLACKURL }}
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install beautifulsoup4
      - name: Run the script
        run: python jobscraper.py
